# Generated by Django 5.0.6 on 2024-06-10 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flan',
            name='image_url',
            field=models.CharField(max_length=255),
        ),
    ]
