# Generated by Django 5.0.6 on 2024-06-10 07:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_contactform'),
    ]

    operations = [
        migrations.AddField(
            model_name='flan',
            name='normalized_name',
            field=models.CharField(default=django.utils.timezone.now, editable=False, max_length=64),
            preserve_default=False,
        ),
    ]
