# Generated by Django 5.0.6 on 2024-06-11 21:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_flan_normalized_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='flan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flan',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
